/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as SessionIdHomeImport } from './routes/$sessionId/home'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const SessionIdHomeRoute = SessionIdHomeImport.update({
  id: '/$sessionId/home',
  path: '/$sessionId/home',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$sessionId/home': {
      id: '/$sessionId/home'
      path: '/$sessionId/home'
      fullPath: '/$sessionId/home'
      preLoaderRoute: typeof SessionIdHomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$sessionId/home': typeof SessionIdHomeRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$sessionId/home': typeof SessionIdHomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$sessionId/home': typeof SessionIdHomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/login' | '/$sessionId/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/$sessionId/home'
  id: '__root__' | '/about' | '/login' | '/$sessionId/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SessionIdHomeRoute: typeof SessionIdHomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SessionIdHomeRoute: SessionIdHomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/login",
        "/$sessionId/home"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$sessionId/home": {
      "filePath": "$sessionId/home.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
