/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthSessionIdHomeImport } from './routes/auth/$sessionId/home'
import { Route as AuthSessionIdDashIdOpendashImport } from './routes/auth/$sessionId/$dashId/open_dash'
import { Route as AuthSessionIdDashIdCurrentdashImport } from './routes/auth/$sessionId/$dashId/current_dash'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSessionIdHomeRoute = AuthSessionIdHomeImport.update({
  id: '/auth/$sessionId/home',
  path: '/auth/$sessionId/home',
  getParentRoute: () => rootRoute,
} as any)

const AuthSessionIdDashIdOpendashRoute =
  AuthSessionIdDashIdOpendashImport.update({
    id: '/auth/$sessionId/$dashId/open_dash',
    path: '/auth/$sessionId/$dashId/open_dash',
    getParentRoute: () => rootRoute,
  } as any)

const AuthSessionIdDashIdCurrentdashRoute =
  AuthSessionIdDashIdCurrentdashImport.update({
    id: '/auth/$sessionId/$dashId/current_dash',
    path: '/auth/$sessionId/$dashId/current_dash',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/$sessionId/home': {
      id: '/auth/$sessionId/home'
      path: '/auth/$sessionId/home'
      fullPath: '/auth/$sessionId/home'
      preLoaderRoute: typeof AuthSessionIdHomeImport
      parentRoute: typeof rootRoute
    }
    '/auth/$sessionId/$dashId/current_dash': {
      id: '/auth/$sessionId/$dashId/current_dash'
      path: '/auth/$sessionId/$dashId/current_dash'
      fullPath: '/auth/$sessionId/$dashId/current_dash'
      preLoaderRoute: typeof AuthSessionIdDashIdCurrentdashImport
      parentRoute: typeof rootRoute
    }
    '/auth/$sessionId/$dashId/open_dash': {
      id: '/auth/$sessionId/$dashId/open_dash'
      path: '/auth/$sessionId/$dashId/open_dash'
      fullPath: '/auth/$sessionId/$dashId/open_dash'
      preLoaderRoute: typeof AuthSessionIdDashIdOpendashImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/auth': typeof AuthIndexRoute
  '/auth/$sessionId/home': typeof AuthSessionIdHomeRoute
  '/auth/$sessionId/$dashId/current_dash': typeof AuthSessionIdDashIdCurrentdashRoute
  '/auth/$sessionId/$dashId/open_dash': typeof AuthSessionIdDashIdOpendashRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/auth': typeof AuthIndexRoute
  '/auth/$sessionId/home': typeof AuthSessionIdHomeRoute
  '/auth/$sessionId/$dashId/current_dash': typeof AuthSessionIdDashIdCurrentdashRoute
  '/auth/$sessionId/$dashId/open_dash': typeof AuthSessionIdDashIdOpendashRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/$sessionId/home': typeof AuthSessionIdHomeRoute
  '/auth/$sessionId/$dashId/current_dash': typeof AuthSessionIdDashIdCurrentdashRoute
  '/auth/$sessionId/$dashId/open_dash': typeof AuthSessionIdDashIdOpendashRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/auth'
    | '/auth/$sessionId/home'
    | '/auth/$sessionId/$dashId/current_dash'
    | '/auth/$sessionId/$dashId/open_dash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/auth'
    | '/auth/$sessionId/home'
    | '/auth/$sessionId/$dashId/current_dash'
    | '/auth/$sessionId/$dashId/open_dash'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/auth/'
    | '/auth/$sessionId/home'
    | '/auth/$sessionId/$dashId/current_dash'
    | '/auth/$sessionId/$dashId/open_dash'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSessionIdHomeRoute: typeof AuthSessionIdHomeRoute
  AuthSessionIdDashIdCurrentdashRoute: typeof AuthSessionIdDashIdCurrentdashRoute
  AuthSessionIdDashIdOpendashRoute: typeof AuthSessionIdDashIdOpendashRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSessionIdHomeRoute: AuthSessionIdHomeRoute,
  AuthSessionIdDashIdCurrentdashRoute: AuthSessionIdDashIdCurrentdashRoute,
  AuthSessionIdDashIdOpendashRoute: AuthSessionIdDashIdOpendashRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/auth/",
        "/auth/$sessionId/home",
        "/auth/$sessionId/$dashId/current_dash",
        "/auth/$sessionId/$dashId/open_dash"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/auth/$sessionId/home": {
      "filePath": "auth/$sessionId/home.tsx"
    },
    "/auth/$sessionId/$dashId/current_dash": {
      "filePath": "auth/$sessionId/$dashId/current_dash.tsx"
    },
    "/auth/$sessionId/$dashId/open_dash": {
      "filePath": "auth/$sessionId/$dashId/open_dash.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
